- id: oodobohSheuX7ic5
  alias: 10 leaving Home - everything off
  description: ''
  trigger:
  - entity_id: group.all_persons
    platform: state
    to: not_home
    for:
      hours: 0
      minutes: 15
      seconds: 0
  action:
  - data:
      entity_id: all
    service: light.turn_off
  - data:
      entity_id: all
    service: media_player.media_stop
  - data:
      entity_id: all
    service: media_player.turn_off
  mode: single
- id: '1590769016333'
  alias: Heating - Bed Room - Window open - off
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 8dbec2681f6b4fa2a8deed7eaaba8367
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_2
    domain: binary_sensor
  condition: []
  action:
  - device_id: 2d5c144767a1418588125d20c8917c19
    domain: climate
    entity_id: climate.fritz_dect_301_schlafzimmer
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1590769182078'
  alias: Heating - Bed Room - Window close - on
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 8dbec2681f6b4fa2a8deed7eaaba8367
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_2
    domain: binary_sensor
  condition: []
  action:
  - device_id: 2d5c144767a1418588125d20c8917c19
    domain: climate
    entity_id: climate.fritz_dect_301_schlafzimmer
    type: set_hvac_mode
    hvac_mode: heat
  - service: script.heating_bedroom_set_preset_comfort
    data: {}
  mode: single
- id: '1590773879107'
  alias: 10 leaving home - Heating - eco
  description: ''
  trigger:
  - entity_id:
    - group.all_persons
    platform: state
    to: not_home
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - data:
      entity_id: all
      preset_mode: eco
    service: climate.set_preset_mode
  mode: single
- id: '1590824968802'
  alias: 10 coming home - Heating - comfort
  description: ''
  trigger:
  - entity_id: group.all_persons
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: all
      preset_mode: comfort
    service: climate.set_preset_mode
  mode: single
- id: '1597827460793'
  alias: wake up Martin - Light
  description: ''
  trigger:
  - platform: time_pattern
    seconds: '0'
  condition:
  - condition: state
    entity_id: person.martin
    state: home
  - condition: template
    value_template: '{{ ((((state_attr(''sensor.phone_martin_next_alarm'', ''Time
      in Milliseconds'') | int / 1000) - (utcnow().strftime("%s") | int)) / 60) |
      int) == 30 }}'
  action:
  - data:
      brightness: 255
      color_temp: 447
      effect: none
      entity_id: light.schlafzimmer
      transition: 1800
    service: light.turn_on
  mode: single
- id: '1602935712311'
  alias: Heating - Bath - Window close - on
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 418e8778106a11eba4bbe7d8d2031815
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
    domain: binary_sensor
  condition: []
  action:
  - device_id: 42b629f30d4a11eba25a1b41c9e5b7dd
    domain: climate
    entity_id: climate.fritz_dect_301_bad
    type: set_hvac_mode
    hvac_mode: heat
  - service: script.heating_bath_set_preset_comfort
    data: {}
  mode: single
- id: '1602936184216'
  alias: Heating - Bath - Window open - off
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 418e8778106a11eba4bbe7d8d2031815
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
    domain: binary_sensor
  condition: []
  action:
  - device_id: 42b629f30d4a11eba25a1b41c9e5b7dd
    domain: climate
    entity_id: climate.fritz_dect_301_bad
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1607074534569'
  alias: 10 Heating - perimeter - comfort
  description: ''
  trigger:
  - platform: zone
    entity_id: person.martin
    zone: zone.heating_perimeter
    event: enter
  condition: []
  action:
  - service: climate.set_preset_mode
    data:
      entity_id: all
      preset_mode: comfort
  mode: single
- id: '1607447231556'
  alias: Flood Kitchen - alarm
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 8c643a776f04c5ba3f282bd9a2335e91
    entity_id: binary_sensor.lumi_lumi_sensor_wleak_aq1_6fbb6404_ias_zone
    domain: binary_sensor
  condition: []
  action:
  - service: notify.notify
    data:
      message: Achtung! Wasserleck in der Kueche!
      data:
        channel: Alarm
  mode: single
- id: '1610097482157'
  alias: 10 coming home - Lights on
  description: ''
  trigger:
  - platform: state
    entity_id: group.all_persons
    to: home
  condition:
  - condition: sun
    after: sunset
  action:
  - service: light.turn_on
    data:
      entity_id: all
  mode: single
- id: '1626011048565'
  alias: Flood Kitchen - Sonos Alarm
  description: ''
  trigger:
  - platform: time_pattern
    seconds: '00'
  condition:
  - type: is_moist
    condition: device
    device_id: 8c643a776f04c5ba3f282bd9a2335e91
    entity_id: binary_sensor.lumi_lumi_sensor_wleak_aq1_6fbb6404_ias_zone
    domain: binary_sensor
  action:
  - service: script.sonos_alarm_water_leakage_kitchen
    data: {}
  mode: single
- id: '1634349031346'
  alias: 99 Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.notify
        data:
          message: Battery of {{sensors}} is low.
      threshold: 20
- id: '1636987192840'
  alias: Washing machine has finished - notify
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: d71554b5dea436bf70846fef16fec150
    entity_id: sensor.fritz_dect_210_waschmaschine_power_consumption
    domain: sensor
    below: 1
    for:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: Die Waschmaschine ist fertig.
  mode: single
- id: '1647181130520'
  alias: 20 Heating - Day - comfort
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition:
  - condition: state
    entity_id: group.all_persons
    state: home
  action:
  - service: script.heating_bath_set_preset_comfort
    data: {}
  - service: script.heating_bedroom_set_preset_comfort
    data: {}
  - service: script.heating_livingroom_set_preset_comfort
    data: {}
  - service: script.heating_lab_set_preset_comfort
    data: {}
  mode: single
- id: '1647763277456'
  alias: 20 Heating - Night - eco
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: script.heating_bath_set_preset_eco
    data: {}
  - service: script.heating_bedroom_set_preset_eco
    data: {}
  - service: script.heating_livingroom_set_preset_eco
    data: {}
  - service: script.heating_lab_set_preset_eco
    data: {}
  mode: single
- id: '1656158846249'
  alias: Mausalarm - Falle 1
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 09d050fac85f97325f8bb2526730f0e4
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
    domain: binary_sensor
  condition: []
  action:
  - service: notify.notify
    data:
      message: Mausalarm in Falle 1
  mode: single
- id: '1665397971672'
  alias: Heating - Living Room - Door open - off
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: a946910b39684795301d7d899f3c852c
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_livingroom_opening
    domain: binary_sensor
  condition: []
  action:
  - device_id: 4d166a5960494ba09a7e2f77f40338bc
    domain: climate
    entity_id: climate.fritz_dect_301_wohnzimmer_2
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1665398028741'
  alias: Heating - Living Room - Door closed - on
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: a946910b39684795301d7d899f3c852c
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_livingroom_opening
    domain: binary_sensor
  condition: []
  action:
  - device_id: 4d166a5960494ba09a7e2f77f40338bc
    domain: climate
    entity_id: climate.fritz_dect_301_wohnzimmer_2
    type: set_hvac_mode
    hvac_mode: heat
  - service: script.heating_livingroom_set_preset_comfort
    data: {}
  mode: single
- id: '1665399099491'
  alias: Heating - Lab - Door open - off
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: f3f45fe65da31a719af1f04175148330
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_lab_opening
    domain: binary_sensor
  condition: []
  action:
  - device_id: 42b6a7900d4a11eba1110385b993a2ba
    domain: climate
    entity_id: climate.fritz_dect_301_lab
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1665399269979'
  alias: Heating - Lab - Door closed - on
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: f3f45fe65da31a719af1f04175148330
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_lab_opening
    domain: binary_sensor
  condition: []
  action:
  - device_id: 42b6a7900d4a11eba1110385b993a2ba
    domain: climate
    entity_id: climate.fritz_dect_301_lab
    type: set_hvac_mode
    hvac_mode: heat
  - service: script.heating_lab_set_preset_comfort
    data: {}
  mode: single
- id: '1666596552565'
  alias: 99 Maintenance - Fritz Tools cleanup
  description: ''
  trigger:
  - platform: time
    at: 03:00:00
  condition: []
  action:
  - service: fritz.cleanup
    data:
      device_id: cb7fe6ff2c0d6bfe06046f9003819aaa
  mode: single
- id: '1674492461101'
  alias: 10 leaving home - Kamera 2
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.all_persons
    to: not_home
  condition: []
  action:
  - service: shell_command.kamera2_position
    data:
      position: 1
  mode: single
- id: '1681130457609'
  alias: Kamera 3 - coming home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.all_persons
    to: home
  condition: []
  action:
  - service: shell_command.kamera3_position
    data:
      position: 8
  mode: single
- id: '1681130589564'
  alias: Kamera 3 - leaving home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.all_persons
    to: away
  condition: []
  action:
  - service: shell_command.kamera3_position
    data:
      position: 1
  mode: single
